// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: (typeof import('./src/components/avatar/Avatar.vue'))['default'];
    CompleteProfile: (typeof import('./src/components/user/profile/CompleteProfile.vue'))['default'];
    Editor: (typeof import('./src/components/wang-editor/Editor.vue'))['default'];
    ElAvatar: (typeof import('element-plus/es'))['ElAvatar'];
    ElButton: (typeof import('element-plus/es'))['ElButton'];
    ElDialog: (typeof import('element-plus/es'))['ElDialog'];
    ElDropdown: (typeof import('element-plus/es'))['ElDropdown'];
    ElDropdownItem: (typeof import('element-plus/es'))['ElDropdownItem'];
    ElDropdownMenu: (typeof import('element-plus/es'))['ElDropdownMenu'];
    ElForm: (typeof import('element-plus/es'))['ElForm'];
    ElFormItem: (typeof import('element-plus/es'))['ElFormItem'];
    ElInput: (typeof import('element-plus/es'))['ElInput'];
    ElMenu: (typeof import('element-plus/es'))['ElMenu'];
    ElMenuItem: (typeof import('element-plus/es'))['ElMenuItem'];
    ElPopover: (typeof import('element-plus/es'))['ElPopover'];
    ElTabPane: (typeof import('element-plus/es'))['ElTabPane'];
    ElTabs: (typeof import('element-plus/es'))['ElTabs'];
    ElTooltip: (typeof import('element-plus/es'))['ElTooltip'];
    LoginAccount: (typeof import('./src/components/user/login/LoginAccount.vue'))['default'];
    LoginDialog: (typeof import('./src/components/user/login/LoginDialog.vue'))['default'];
    LoginPanel: (typeof import('./src/components/user/login/LoginPanel.vue'))['default'];
    NavBar: (typeof import('./src/components/navbar/NavBar.vue'))['default'];
    NavBarCenter: (typeof import('./src/components/navbar/cpns/NavBarCenter.vue'))['default'];
    NavBarLeft: (typeof import('./src/components/navbar/cpns/NavBarLeft.vue'))['default'];
    NavBarMoblie: (typeof import('./src/components/navbar/cpns/NavBarMoblie.vue'))['default'];
    NavBarRight: (typeof import('./src/components/navbar/cpns/NavBarRight.vue'))['default'];
    NavBarUser: (typeof import('./src/components/navbar/cpns/NavBarUser.vue'))['default'];
    NavMenu: (typeof import('./src/components/navbar/cpns/NavMenu.vue'))['default'];
    ProfileDialog: (typeof import('./src/components/user/profile/ProfileDialog.vue'))['default'];
    ProfilePanel: (typeof import('./src/components/user/profile/ProfilePanel.vue'))['default'];
    RegisterAccount: (typeof import('./src/components/user/login/RegisterAccount.vue'))['default'];
    RouterLink: (typeof import('vue-router'))['RouterLink'];
    RouterView: (typeof import('vue-router'))['RouterView'];
  }
}
