/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ActionList: typeof import('./components/ActionList.vue')['default']
    Avatar: typeof import('./components/avatar/Avatar.vue')['default']
    Editor: typeof import('./components/wang-editor/Editor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FollowButton: typeof import('./components/FollowButton.vue')['default']
    LoginAccount: typeof import('./components/user/login/LoginAccount.vue')['default']
    LoginPanel: typeof import('./components/user/login/LoginPanel.vue')['default']
    NavBar: typeof import('./components/navbar/NavBar.vue')['default']
    NavBarLeft: typeof import('./components/navbar/cpns/NavBarLeft.vue')['default']
    NavBarRight: typeof import('./components/navbar/cpns/NavBarRight.vue')['default']
    NavBarUser: typeof import('./components/navbar/cpns/NavBarUser.vue')['default']
    NavMenu: typeof import('./components/navbar/cpns/NavMenu.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    ProfilePanel: typeof import('./components/user/profile/ProfilePanel.vue')['default']
    RegisterAccount: typeof import('./components/user/login/RegisterAccount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDialog: typeof import('./components/user/UserDialog.vue')['default']
    ValidCode: typeof import('./components/ValidCode.vue')['default']
  }
}
