// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Avatar: typeof import('./components/avatar/Avatar.vue')['default']
    CompleteProfile: typeof import('./components/user/profile/CompleteProfile.vue')['default']
    Editor: typeof import('./components/wang-editor/Editor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDrawer: typeof import('element-plus/es')['ElDrawer']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    LoginAccount: typeof import('./components/user/login/LoginAccount.vue')['default']
    LoginPanel: typeof import('./components/user/login/LoginPanel.vue')['default']
    NavBar: typeof import('./components/navbar/NavBar.vue')['default']
    NavBarCenter: typeof import('./components/navbar/cpns/NavBarCenter.vue')['default']
    NavBarLeft: typeof import('./components/navbar/cpns/NavBarLeft.vue')['default']
    NavBarRight: typeof import('./components/navbar/cpns/NavBarRight.vue')['default']
    NavBarUser: typeof import('./components/navbar/cpns/NavBarUser.vue')['default']
    NavMenu: typeof import('./components/navbar/cpns/NavMenu.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    RegisterAccount: typeof import('./components/user/login/RegisterAccount.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserDialog: typeof import('./components/user/UserDialog.vue')['default']
    ValidCode: typeof import('./components/ValidCode.vue')['default']
  }
}
