/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleAction: typeof import('./components/list/cpns/ArticleAction.vue')['default']
    Avatar: typeof import('./components/avatar/Avatar.vue')['default']
    CommentAction: typeof import('./components/list/cpns/CommentAction.vue')['default']
    CommentSvg: typeof import('./components/icon/cpns/CommentSvg.vue')['default']
    Editor: typeof import('./components/wang-editor/Editor.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    ElBacktop: typeof import('element-plus/es')['ElBacktop']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCascader: typeof import('element-plus/es')['ElCascader']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSkeleton: typeof import('element-plus/es')['ElSkeleton']
    ElStep: typeof import('element-plus/es')['ElStep']
    ElSteps: typeof import('element-plus/es')['ElSteps']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    FollowButton: typeof import('./components/FollowButton.vue')['default']
    IBack: typeof import('~icons/ep/back')['default']
    ICoin: typeof import('~icons/ep/coin')['default']
    Icon: typeof import('./components/icon/Icon.vue')['default']
    ICoordinate: typeof import('~icons/ep/coordinate')['default']
    IEdit: typeof import('~icons/ep/edit')['default']
    IEditPen: typeof import('~icons/ep/edit-pen')['default']
    ISuccessFilled: typeof import('~icons/ep/success-filled')['default']
    ISuitcase: typeof import('~icons/ep/suitcase')['default']
    ITakeawayBox: typeof import('~icons/ep/takeaway-box')['default']
    LikeSvg: typeof import('./components/icon/cpns/LikeSvg.vue')['default']
    ListAction: typeof import('./components/list/cpns/ListAction.vue')['default']
    ListItem: typeof import('./components/list/ListItem.vue')['default']
    LoginAccount: typeof import('./components/user/login/LoginAccount.vue')['default']
    LoginPanel: typeof import('./components/user/login/LoginPanel.vue')['default']
    NavBar: typeof import('./components/navbar/NavBar.vue')['default']
    NavBarLeft: typeof import('./components/navbar/cpns/NavBarLeft.vue')['default']
    NavBarRight: typeof import('./components/navbar/cpns/NavBarRight.vue')['default']
    NavBarUser: typeof import('./components/navbar/cpns/NavBarUser.vue')['default']
    NavMenu: typeof import('./components/navbar/cpns/NavMenu.vue')['default']
    Page: typeof import('./components/Page.vue')['default']
    ProfilePanel: typeof import('./components/user/profile/ProfilePanel.vue')['default']
    RegisterAccount: typeof import('./components/user/login/RegisterAccount.vue')['default']
    ReportDialog: typeof import('./components/dialog/ReportDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StarSvg: typeof import('./components/icon/cpns/StarSvg.vue')['default']
    UserDialog: typeof import('./components/user/UserDialog.vue')['default']
    ViewSvg: typeof import('./components/icon/cpns/ViewSvg.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
